### ISSUE TITLE
Can't run demo: integer result unrepresentable

### ISSUE THREAD

**Issue by opiepj** [kripken/BananaBread#67]
After build and run, I get this error in the console:
`Integer result unrepresentable`
![image](https://user-images.githubusercontent.com/7416676/32965914-02c0c652-cb8d-11e7-834d-a9ea7f71c5ba.png)

Which causes the game to freeze when finished loading:
![image](https://user-images.githubusercontent.com/7416676/32965969-2d2fd194-cb8d-11e7-860f-b5389c521650.png)

Also the output bb.html inserts:
`<script async src="game/gl-matrix.js.js"></script>`
instead of 
`<script async src="game/gl-matrix.js"></script>`

**Comment by thomaswmanion** [comment]
I got the same errors too. Running on a Macbook Pro -

Build log contains a couple warnings that look troublesome -
checking dynamic linker characteristics... ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
WARNING:root:emcc: cannot find library "SDL_image"
WARNING:root:emcc: cannot find library "SDL_mixer"
WARNING:root:emcc: cannot find library "z"

Could these be errors instead of warnings maybe?

**Comment by kripken** [comment]
That error was because the way wasm handles trapping in the toolchain changed. I pushed a commit with updated build flags now.

> Could these be errors instead of warnings maybe?

There is an emcc option for that, but it's off by default.

**Comment by opiepj** [comment]
@kripken Thank you that worked! Also great project, I want to build an RTS demo based on your work. Any advice on how to get started?

**Comment by kripken** [comment]
Depends what you're adding - new levels, or new code, or something else?

**Comment by thomaswmanion** [comment]
Thanks for fixing! This is so cool. I'm very excited to make that game with @opiepj .

**Comment by opiepj** [comment]
New code to the game, how much of the engine would I need to modify if wanted to do something like a top-down RTS? Anything to be concerned?

**Comment by kripken** [comment]
I think it's more suited for FPS games. But you could ask on the Cube 2 forums, maybe other people tried to use it that way.
